apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-react
  template:
    metadata:
      labels:
        app: frontend-react
    spec:
      containers:
        - name: frontend-container
          image: keyssong/react-multithread-interno:latest  
          imagePullPolicy: Always              
          ports:
            - containerPort: 5174                