apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-react
  ports:
    - protocol: TCP
      port: 5174
      targetPort: 5174
      nodePort: 31007
  type: NodePort    