apiVersion: v1
kind: Service
metadata:
  name: multithread-interno-service
spec:
  selector:
    app: multithread-interno-react
  ports:
    - protocol: TCP
      port: 5174
      targetPort: 5174
      nodePort: 31007
  type: NodePort    