apiVersion: apps/v1
kind: Deployment
metadata:
  name: multithread-interno-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multithread-interno-react
  template:
    metadata:
      labels:
        app: multithread-interno-react
    spec:
      containers:
        - name: multithread-interno-container
          image: keyssong/react-multithread-interno:latest  
          imagePullPolicy: Always              
          ports:
            - containerPort: 5174                